apiVersion: v1
kind: Pod
metadata:
  name: cloud-init-driven
  annotations:
    kubernetes.io/target-runtime: virtlet.cloud
    VirtletDiskDriver: virtio
    VirtletCloudInitUserDataScript: |
      run:
        - PUT: /app/
          command: "runscript /run/app"
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: cloud-init-driven
    image: virtlet.cloud/172.16.117.45/osv-cinit/osv-cinit.qemu
