apiVersion: v1
kind: Pod
metadata:
  name: basic
  annotations:
    kubernetes.io/target-runtime: virtlet.cloud
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: basic
    image: virtlet.cloud/172.16.117.45/osv-basic/osv-basic.qemu
