apiVersion: v1
kind: Pod
metadata:
  name: volume-attached
  annotations:
    kubernetes.io/target-runtime: virtlet.cloud
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: extraRuntime
            operator: In
            values:
            - virtlet
  containers:
  - name: volume-attached
    image: virtlet.cloud/172.16.117.45/osv-volumes/osv-volumes.qemu
    imagePullPolicy: Always
  volumes:
  - name: volume2
    flexVolume:
      driver: "virtlet/flexvolume_driver"
      options:
        type: qcow2
        capacity: 512MB
